/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'error-container': '#93000a',
        'tertiary-container': '#9ba8eb',
        'primary-fixed': '#ffe08f',
        'on-error-container': '#ffdad6',
        'surface-container-high': '#2a2a2a',
        'surface-bright': '#3a3939',
        'background': '#0a0a0a',
        'error': '#ffb4ab',
        'outline': '#99907e',
        'on-primary-container': '#503d00',
        'inverse-surface': '#e5e2e1',
        'secondary-container': '#4e4638',
        'tertiary-fixed-dim': '#b9c3ff',
        'on-primary': '#3d2e00',
        'on-tertiary-fixed-variant': '#35437e',
        'primary-fixed-dim': '#e6c364',
        'primary-container': '#c9a84c',
        'on-primary-fixed-variant': '#584400',
        'surface-dim': '#131313',
        'on-secondary-fixed-variant': '#4e4638',
        'on-surface-variant': '#d0c5b2',
        'on-tertiary-container': '#2e3b77',
        'surface-container-lowest': '#0e0e0e',
        'on-tertiary': '#1e2b66',
        'primary': '#e6c364',
        'surface-variant': '#353534',
        'on-secondary-fixed': '#211b0f',
        'secondary-fixed-dim': '#d1c5b3',
        'on-background': '#e5e2e1',
        'inverse-primary': '#755b00',
        'surface-container-low': '#1c1b1b',
        'secondary': '#d1c5b3',
        'on-secondary-container': '#bfb4a2',
        'surface-container': '#201f1f',
        'on-primary-fixed': '#241a00',
        'on-secondary': '#362f23',
        'on-tertiary-fixed': '#041451',
        'tertiary-fixed': '#dde1ff',
        'surface': '#131313',
        'secondary-fixed': '#eee1ce',
        'inverse-on-surface': '#313030',
        'outline-variant': '#4d4637',
        'on-surface': '#e5e2e1',
        'tertiary': '#b9c4ff',
        'surface-tint': '#e6c364',
        'on-error': '#690005',
        'surface-container-highest': '#353534',
        'warm-white-text': '#EDE8DF',
        'secondary-text': '#8A8070',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Cormorant Garamond', 'serif'],
        body: ['Lora', 'serif'],
        label: ['Josefin Sans', 'sans-serif'],
        technical: ['DM Mono', 'monospace'],
        mono: ['DM Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}
